repos:
  # --- Hooks prontos da comunidade ---
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: pretty-format-json # Formata JSON
        args: ["--autofix"]


  - repo: local
    hooks:
      - id: checkstyle
        name: Checkstyle Java
        entry: java -jar utils/checkstyle-11.0.1-all.jar -c utils/google_checks.xml
        language: system
        types: [java]

  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.23.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-conventional']
